(cl:in-package uv_msgs-srv)
(cl:export '(X_MIN-VAL
          X_MIN
          X_MAX-VAL
          X_MAX
          X_INC-VAL
          X_INC
          Y_MIN-VAL
          Y_MIN
          Y_MAX-VAL
          Y_MAX
          Y_INC-VAL
          Y_INC
          Z_MIN-VAL
          Z_MIN
          Z_MAX-VAL
          Z_MAX
          Z_INC-VAL
          Z_INC
          R_MIN-VAL
          R_MIN
          R_MAX-VAL
          R_MAX
          R_INC-VAL
          R_INC
          P_MIN-VAL
          P_MIN
          P_MAX-VAL
          P_MAX
          P_INC-VAL
          P_INC
          W_MIN-VAL
          W_MIN
          W_MAX-VAL
          W_MAX
          W_INC-VAL
          W_INC
          SEEDS_PER-VAL
          SEEDS_PER
          SEEDS_STD_T-VAL
          SEEDS_STD_T
          SEEDS_STD_R-VAL
          SEEDS_STD_R
          CYCLE_STD_T-VAL
          CYCLE_STD_T
          CYCLE_STD_R-VAL
          CYCLE_STD_R
          NUM_PARTICLES-VAL
          NUM_PARTICLES
))