// Generated by gencpp from file cwru_opencv_common/image_label.msg
// DO NOT EDIT!


#ifndef CWRU_OPENCV_COMMON_MESSAGE_IMAGE_LABEL_H
#define CWRU_OPENCV_COMMON_MESSAGE_IMAGE_LABEL_H

#include <ros/service_traits.h>


#include <cwru_opencv_common/image_labelRequest.h>
#include <cwru_opencv_common/image_labelResponse.h>


namespace cwru_opencv_common
{

struct image_label
{

typedef image_labelRequest Request;
typedef image_labelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct image_label
} // namespace cwru_opencv_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cwru_opencv_common::image_label > {
  static const char* value()
  {
    return "b3ecebcd9795fbae5831a134ed461482";
  }

  static const char* value(const ::cwru_opencv_common::image_label&) { return value(); }
};

template<>
struct DataType< ::cwru_opencv_common::image_label > {
  static const char* value()
  {
    return "cwru_opencv_common/image_label";
  }

  static const char* value(const ::cwru_opencv_common::image_label&) { return value(); }
};


// service_traits::MD5Sum< ::cwru_opencv_common::image_labelRequest> should match
// service_traits::MD5Sum< ::cwru_opencv_common::image_label >
template<>
struct MD5Sum< ::cwru_opencv_common::image_labelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cwru_opencv_common::image_label >::value();
  }
  static const char* value(const ::cwru_opencv_common::image_labelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cwru_opencv_common::image_labelRequest> should match
// service_traits::DataType< ::cwru_opencv_common::image_label >
template<>
struct DataType< ::cwru_opencv_common::image_labelRequest>
{
  static const char* value()
  {
    return DataType< ::cwru_opencv_common::image_label >::value();
  }
  static const char* value(const ::cwru_opencv_common::image_labelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cwru_opencv_common::image_labelResponse> should match
// service_traits::MD5Sum< ::cwru_opencv_common::image_label >
template<>
struct MD5Sum< ::cwru_opencv_common::image_labelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cwru_opencv_common::image_label >::value();
  }
  static const char* value(const ::cwru_opencv_common::image_labelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cwru_opencv_common::image_labelResponse> should match
// service_traits::DataType< ::cwru_opencv_common::image_label >
template<>
struct DataType< ::cwru_opencv_common::image_labelResponse>
{
  static const char* value()
  {
    return DataType< ::cwru_opencv_common::image_label >::value();
  }
  static const char* value(const ::cwru_opencv_common::image_labelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CWRU_OPENCV_COMMON_MESSAGE_IMAGE_LABEL_H
