// Generated by gencpp from file uv_msgs/pf_anneal.msg
// DO NOT EDIT!


#ifndef UV_MSGS_MESSAGE_PF_ANNEAL_H
#define UV_MSGS_MESSAGE_PF_ANNEAL_H

#include <ros/service_traits.h>


#include <uv_msgs/pf_annealRequest.h>
#include <uv_msgs/pf_annealResponse.h>


namespace uv_msgs
{

struct pf_anneal
{

typedef pf_annealRequest Request;
typedef pf_annealResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pf_anneal
} // namespace uv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uv_msgs::pf_anneal > {
  static const char* value()
  {
    return "6291b620f34cf0f1f6b982289d0728a6";
  }

  static const char* value(const ::uv_msgs::pf_anneal&) { return value(); }
};

template<>
struct DataType< ::uv_msgs::pf_anneal > {
  static const char* value()
  {
    return "uv_msgs/pf_anneal";
  }

  static const char* value(const ::uv_msgs::pf_anneal&) { return value(); }
};


// service_traits::MD5Sum< ::uv_msgs::pf_annealRequest> should match
// service_traits::MD5Sum< ::uv_msgs::pf_anneal >
template<>
struct MD5Sum< ::uv_msgs::pf_annealRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uv_msgs::pf_anneal >::value();
  }
  static const char* value(const ::uv_msgs::pf_annealRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_msgs::pf_annealRequest> should match
// service_traits::DataType< ::uv_msgs::pf_anneal >
template<>
struct DataType< ::uv_msgs::pf_annealRequest>
{
  static const char* value()
  {
    return DataType< ::uv_msgs::pf_anneal >::value();
  }
  static const char* value(const ::uv_msgs::pf_annealRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uv_msgs::pf_annealResponse> should match
// service_traits::MD5Sum< ::uv_msgs::pf_anneal >
template<>
struct MD5Sum< ::uv_msgs::pf_annealResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uv_msgs::pf_anneal >::value();
  }
  static const char* value(const ::uv_msgs::pf_annealResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_msgs::pf_annealResponse> should match
// service_traits::DataType< ::uv_msgs::pf_anneal >
template<>
struct DataType< ::uv_msgs::pf_annealResponse>
{
  static const char* value()
  {
    return DataType< ::uv_msgs::pf_anneal >::value();
  }
  static const char* value(const ::uv_msgs::pf_annealResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UV_MSGS_MESSAGE_PF_ANNEAL_H
