// Generated by gencpp from file uv_msgs/pf_annealResponse.msg
// DO NOT EDIT!


#ifndef UV_MSGS_MESSAGE_PF_ANNEALRESPONSE_H
#define UV_MSGS_MESSAGE_PF_ANNEALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uv_msgs
{
template <class ContainerAllocator>
struct pf_annealResponse_
{
  typedef pf_annealResponse_<ContainerAllocator> Type;

  pf_annealResponse_()
    {
    }
  pf_annealResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::uv_msgs::pf_annealResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uv_msgs::pf_annealResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pf_annealResponse_

typedef ::uv_msgs::pf_annealResponse_<std::allocator<void> > pf_annealResponse;

typedef boost::shared_ptr< ::uv_msgs::pf_annealResponse > pf_annealResponsePtr;
typedef boost::shared_ptr< ::uv_msgs::pf_annealResponse const> pf_annealResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uv_msgs::pf_annealResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace uv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uv_msgs::pf_annealResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uv_msgs::pf_annealResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uv_msgs::pf_annealResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::uv_msgs::pf_annealResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uv_msgs/pf_annealResponse";
  }

  static const char* value(const ::uv_msgs::pf_annealResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::uv_msgs::pf_annealResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pf_annealResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uv_msgs::pf_annealResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::uv_msgs::pf_annealResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UV_MSGS_MESSAGE_PF_ANNEALRESPONSE_H
