// Generated by gencpp from file uv_msgs/pf_graspResponse.msg
// DO NOT EDIT!


#ifndef UV_MSGS_MESSAGE_PF_GRASPRESPONSE_H
#define UV_MSGS_MESSAGE_PF_GRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uv_msgs
{
template <class ContainerAllocator>
struct pf_graspResponse_
{
  typedef pf_graspResponse_<ContainerAllocator> Type;

  pf_graspResponse_()
    : status(false)  {
    }
  pf_graspResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::uv_msgs::pf_graspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uv_msgs::pf_graspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pf_graspResponse_

typedef ::uv_msgs::pf_graspResponse_<std::allocator<void> > pf_graspResponse;

typedef boost::shared_ptr< ::uv_msgs::pf_graspResponse > pf_graspResponsePtr;
typedef boost::shared_ptr< ::uv_msgs::pf_graspResponse const> pf_graspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uv_msgs::pf_graspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uv_msgs::pf_graspResponse_<ContainerAllocator1> & lhs, const ::uv_msgs::pf_graspResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uv_msgs::pf_graspResponse_<ContainerAllocator1> & lhs, const ::uv_msgs::pf_graspResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uv_msgs::pf_graspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uv_msgs::pf_graspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uv_msgs::pf_graspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::uv_msgs::pf_graspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uv_msgs/pf_graspResponse";
  }

  static const char* value(const ::uv_msgs::pf_graspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool status\n"
"\n"
;
  }

  static const char* value(const ::uv_msgs::pf_graspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pf_graspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uv_msgs::pf_graspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uv_msgs::pf_graspResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UV_MSGS_MESSAGE_PF_GRASPRESPONSE_H
