// Generated by gencpp from file uv_msgs/pf_grasp.msg
// DO NOT EDIT!


#ifndef UV_MSGS_MESSAGE_PF_GRASP_H
#define UV_MSGS_MESSAGE_PF_GRASP_H

#include <ros/service_traits.h>


#include <uv_msgs/pf_graspRequest.h>
#include <uv_msgs/pf_graspResponse.h>


namespace uv_msgs
{

struct pf_grasp
{

typedef pf_graspRequest Request;
typedef pf_graspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pf_grasp
} // namespace uv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uv_msgs::pf_grasp > {
  static const char* value()
  {
    return "0f0796a15122ded309c5568ad00da46d";
  }

  static const char* value(const ::uv_msgs::pf_grasp&) { return value(); }
};

template<>
struct DataType< ::uv_msgs::pf_grasp > {
  static const char* value()
  {
    return "uv_msgs/pf_grasp";
  }

  static const char* value(const ::uv_msgs::pf_grasp&) { return value(); }
};


// service_traits::MD5Sum< ::uv_msgs::pf_graspRequest> should match
// service_traits::MD5Sum< ::uv_msgs::pf_grasp >
template<>
struct MD5Sum< ::uv_msgs::pf_graspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uv_msgs::pf_grasp >::value();
  }
  static const char* value(const ::uv_msgs::pf_graspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_msgs::pf_graspRequest> should match
// service_traits::DataType< ::uv_msgs::pf_grasp >
template<>
struct DataType< ::uv_msgs::pf_graspRequest>
{
  static const char* value()
  {
    return DataType< ::uv_msgs::pf_grasp >::value();
  }
  static const char* value(const ::uv_msgs::pf_graspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uv_msgs::pf_graspResponse> should match
// service_traits::MD5Sum< ::uv_msgs::pf_grasp >
template<>
struct MD5Sum< ::uv_msgs::pf_graspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uv_msgs::pf_grasp >::value();
  }
  static const char* value(const ::uv_msgs::pf_graspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_msgs::pf_graspResponse> should match
// service_traits::DataType< ::uv_msgs::pf_grasp >
template<>
struct DataType< ::uv_msgs::pf_graspResponse>
{
  static const char* value()
  {
    return DataType< ::uv_msgs::pf_grasp >::value();
  }
  static const char* value(const ::uv_msgs::pf_graspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UV_MSGS_MESSAGE_PF_GRASP_H
