// Generated by gencpp from file uv_msgs/pf_reseedResponse.msg
// DO NOT EDIT!


#ifndef UV_MSGS_MESSAGE_PF_RESEEDRESPONSE_H
#define UV_MSGS_MESSAGE_PF_RESEEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uv_msgs
{
template <class ContainerAllocator>
struct pf_reseedResponse_
{
  typedef pf_reseedResponse_<ContainerAllocator> Type;

  pf_reseedResponse_()
    : num_particles(0)  {
    }
  pf_reseedResponse_(const ContainerAllocator& _alloc)
    : num_particles(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_particles_type;
  _num_particles_type num_particles;





  typedef boost::shared_ptr< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pf_reseedResponse_

typedef ::uv_msgs::pf_reseedResponse_<std::allocator<void> > pf_reseedResponse;

typedef boost::shared_ptr< ::uv_msgs::pf_reseedResponse > pf_reseedResponsePtr;
typedef boost::shared_ptr< ::uv_msgs::pf_reseedResponse const> pf_reseedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uv_msgs::pf_reseedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uv_msgs::pf_reseedResponse_<ContainerAllocator1> & lhs, const ::uv_msgs::pf_reseedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.num_particles == rhs.num_particles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uv_msgs::pf_reseedResponse_<ContainerAllocator1> & lhs, const ::uv_msgs::pf_reseedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3e7a05396001d2e02f04b13547a3da2";
  }

  static const char* value(const ::uv_msgs::pf_reseedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3e7a05396001d2eULL;
  static const uint64_t static_value2 = 0x02f04b13547a3da2ULL;
};

template<class ContainerAllocator>
struct DataType< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uv_msgs/pf_reseedResponse";
  }

  static const char* value(const ::uv_msgs::pf_reseedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 num_particles\n"
"\n"
;
  }

  static const char* value(const ::uv_msgs::pf_reseedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_particles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pf_reseedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uv_msgs::pf_reseedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uv_msgs::pf_reseedResponse_<ContainerAllocator>& v)
  {
    s << indent << "num_particles: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_particles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UV_MSGS_MESSAGE_PF_RESEEDRESPONSE_H
