// Generated by gencpp from file uv_msgs/pf_reseed.msg
// DO NOT EDIT!


#ifndef UV_MSGS_MESSAGE_PF_RESEED_H
#define UV_MSGS_MESSAGE_PF_RESEED_H

#include <ros/service_traits.h>


#include <uv_msgs/pf_reseedRequest.h>
#include <uv_msgs/pf_reseedResponse.h>


namespace uv_msgs
{

struct pf_reseed
{

typedef pf_reseedRequest Request;
typedef pf_reseedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pf_reseed
} // namespace uv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uv_msgs::pf_reseed > {
  static const char* value()
  {
    return "785c60e5b9579c5ec461ae5d33e9f1f7";
  }

  static const char* value(const ::uv_msgs::pf_reseed&) { return value(); }
};

template<>
struct DataType< ::uv_msgs::pf_reseed > {
  static const char* value()
  {
    return "uv_msgs/pf_reseed";
  }

  static const char* value(const ::uv_msgs::pf_reseed&) { return value(); }
};


// service_traits::MD5Sum< ::uv_msgs::pf_reseedRequest> should match
// service_traits::MD5Sum< ::uv_msgs::pf_reseed >
template<>
struct MD5Sum< ::uv_msgs::pf_reseedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uv_msgs::pf_reseed >::value();
  }
  static const char* value(const ::uv_msgs::pf_reseedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_msgs::pf_reseedRequest> should match
// service_traits::DataType< ::uv_msgs::pf_reseed >
template<>
struct DataType< ::uv_msgs::pf_reseedRequest>
{
  static const char* value()
  {
    return DataType< ::uv_msgs::pf_reseed >::value();
  }
  static const char* value(const ::uv_msgs::pf_reseedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uv_msgs::pf_reseedResponse> should match
// service_traits::MD5Sum< ::uv_msgs::pf_reseed >
template<>
struct MD5Sum< ::uv_msgs::pf_reseedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uv_msgs::pf_reseed >::value();
  }
  static const char* value(const ::uv_msgs::pf_reseedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uv_msgs::pf_reseedResponse> should match
// service_traits::DataType< ::uv_msgs::pf_reseed >
template<>
struct DataType< ::uv_msgs::pf_reseedResponse>
{
  static const char* value()
  {
    return DataType< ::uv_msgs::pf_reseed >::value();
  }
  static const char* value(const ::uv_msgs::pf_reseedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UV_MSGS_MESSAGE_PF_RESEED_H
